language: cpp
sudo: required
compiler:
  - gcc

before_install:
  - sudo bash travis/get_cmake.sh
  - sudo apt-get install -qq

before_script:
  - mkdir build
  - cd build
  - /tmp/cmake-3.7.1/cmake ..

script:
  - pwd
  - make