language: cpp
sudo: required
addons:
    apt:
        sources:
            - llvm-toolchain-precise
            - ubuntu-toolchain-r-test
        packages:
            - clang-3.7
            - g++-5
            - gcc-5
            - cmake-3.6

compiler:
  - clang
  - gcc

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - pwd
  - make